language: java
sudo: required
jdk:
  - openjdk8
cache:  
  directories:  
   - $HOME/.m2  

before_install:
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
    - . /tmp/BuildUtilities/travis-ci/setupenvironment.sh
install: true

script: mvn clean verify

after_success:
- . /tmp/BuildUtilities/travis-ci/deploy.sh pcm2java4KeY releng/edu.kit.kastel.scbs.pcm2java4KeY.updatesite.aggregated final KASTEL-SCBS updatesite

notifications:
  slack:
    secure: zZbcJtpumQTKqe1JtSfh5MQ5UC3fDdI6MWLuoJRTVCKhB5zaYLgylgLHDyJDsoGQSltJ+PATzWUv0IaJzm1jPgyl/aBDN5Y5zZM72evtpxQ8oW0EQ5S4BrOMOxSKMIt6c7GZvXMvJmuCkORTAwPnFzrvntloP5bkjMdZmi9JzX9N92aRt3xMOs1gB7+5zRclFAoAWQZ6dv4aS08vJhhnPanuqPM/cRDW1+0mSTRjuc4fNjUWuohKevxZ6x2bsFk1xL4jRovN69aPAa26v6MW2LyqCN5HaZS2ftd74yv5N+kKxFsE3asQRrVj5N/2c0z/GALaSLUC5R5ZjsAgUz4kaJlg0C8V9GftdLdCNALaUiSVYlesq/M8Tt+xZJSDRb64am4Qddi2+vC/O9PJdjVM9hGQAIPQgQ0PwgiDsIOutVhuqsjob0OdECwrR4oeKzY8Msv5/B7DNIBBll9zv3g1ao7tR2F/o7sT6crSOKbNKLtNbsLbukgwyuPr/b8IZc8+l9it1+BM7sUwQWeF5yKTK0RXGMgjPOdREfarW2hiwUKoYUwffif+1s5cgU98MHi4Q91ZYKKbKrWeEyW/L0Cvybl8RE8z3eXCaMuONxKMF0jTXEkHTKaoDQwyIuhFpjsE9NLQrb5WAT4/iLy3GOov9W3hwe5ap7YLs1DTgOj4Ap0=
